### ISSUE TITLE
Zelda: Majora's Mask: Black screen during beginning animations. (Framebuffer Emulation needed)

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#14]
OS: `Slackware64-current`
`RetroArch-1.3.6-x86_64-1_SBo`

When starting Majora's Mask it will show the nintendo logo and then black screen with sound until it gets to the opening video of the town. The black screen is the portion where it shows the mask seller and it will display properly with mupen64plus-libretro.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-04-105351_1680x1050_scrot.png)
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-04-105422_1680x1050_scrot.png)

**Comment by loganmc10** [comment]
It displays properly on mupen64plus-libretro with GLideN64?

**Comment by orbea** [comment]
Sorry, I was wrong. I forgot `GLIDEN64=1`. It has the same issue and additionally does the town animation far worse...

**Comment by loganmc10** [comment]
It might be because Framebuffer Emulation is disabled (it is disabled in GLupeN64 and mupen64plus-libretro+GLideN64), I'll test it tonight with regular mupen64plus.

Framebuffer Emulation is the last "big feature" that needs to be implemented, but I'm not sure how to get it working with libretro yet. But I'll test tonight to see if that really is the issue here.

**Comment by loganmc10** [comment]
Actually I can test this on my phone with the mupen64plus-ae app.

It is indeed a Framebuffer Emulation issue.

**Comment by loganmc10** [comment]
If anyone wants to take a look, here is an apitrace with Framebuffer Emulation enabled:

https://drive.google.com/file/d/0B8iAuv3fmhb_OFB5QWh3aHh3dzg/view?usp=sharing

**Comment by loganmc10** [comment]
Interestingly, Framebuffer Emulation seems to work with full OpenGL, but not GLES2

**Comment by loganmc10** [comment]
Ok, can you try it with the latest master? You need to use regular OpenGL (no  FORCE_GLES)

**Comment by orbea** [comment]
That seems to mostly work, it will display the missing animations of majora's mask and some backgrounds that did not render before in the town animation.  However it introduced some new issues too. The most problematic is that there is a lot of slow down to the game now, before it ran smoothly with `1280x960` resolution while now its laggy even with `320 x 240`.

Also it will flash a variation of this before the animation of the mask when starting the game.
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-06-153722_1680x1050_scrot.png)

**Comment by orbea** [comment]
Commit https://github.com/loganmc10/GLupeN64/commit/23d4774c3e0d7d70f7b94d6281c86abe5919aac5 also introduced a regression with the opening animation in Super Smash Bros. Mupen64plus-libretro does not have this issue, but interestingly all of the characters will appear faceless with `gln64` unless compiled with `GLIDEN64=1`.

![4](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-06-173513_1680x1050_scrot.png)
![5](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-06-173516_1680x1050_scrot.png)
![6](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-06-173538_1680x1050_scrot.png)

**Comment by loganmc10** [comment]
I'm not seeing those graphical glitches on my laptop, I'll have to test it a bit more to be sure.

**Comment by orbea** [comment]
Interesting, maybe its related to only certain video drivers? I tested that both that commit and the one before, it was certainly the that one which introduced it for me.

**Comment by loganmc10** [comment]
You can try the latest commit to see if the speed improves, you might have to remove retroarch-core-options.cfg

I don't have another device to test right now for those graphical glitches. It might have to do with the Mesa "compat" thing

**Comment by orbea** [comment]
I'm getting a build failure as shown in issue https://github.com/loganmc10/GLupeN64/issues/17 now...

**Comment by loganmc10** [comment]
Sorry about that, should be fixed now

**Comment by orbea** [comment]
Thanks, it builds now.

The speed is much better now, however its still not what it was before. With `320 x 240` and `640 x 480` its mostly reduced to minor audio static and stuttering. Higher resolutions are more affected of course. Its worth noting that `GLIDEN64=1` with mupen64plus also has significant slowdowns, similar to how it was before your recent changes.

Interestingly the rendering issues with Super Smash Bros have vanished, but the issue with Majaro's Mask is still present.

**Comment by loganmc10** [comment]
The speed seems ok on my device, Framebuffer Emulation is more work, so it's not surprising that it's slower. The real test would be to compare this plugin to mupen64plus+GLideN64 to see if the speed issues are with this plugin, or with GLideN64.

When I test it with Majora's Mask on my Intel Graphics Laptop, the speed seems the same with both versions, so I don't think the speed is an issue with the plugin.

Am I ok to close this issue? The minor issue with Majora's Mark doesn't show up for me, and might be because of some Mesa glitch (the forced compatibility profiles aren't guaranteed to work perfectly)

**Comment by orbea** [comment]
I can no longer reproduce the graphical issues or slowdowns with Majora's Mask.
