### ISSUE TITLE
segfault when launching retroarch GUI

### ISSUE THREAD

**Issue by dankcushions** [loganmc10/GLupeN64#38]
built from source by retropie. running it like so:
```
gdb --args /opt/retropie/emulators/retroarch/bin/retroarch --config /opt/retropie/configs/all/retroarch.cfg --appendconfig /opt/retropie/configs/n64/retroarch.cfg -L /opt/retropie/libretrocores/lr-glupen64/glupen64_libretro.so /home/pi/RetroPie/roms/n64/Super\ Mario\ 64\ (USA).n64
```

trace:
```
pi@retropie:~/RetroPie/roms/n64 $ gdb --args /opt/retropie/emulators/retroarch/bin/retroarch --config /opt/retropie/configs/all/retroarch.cfg --appendconfig /opt/retropie/configs/n64/retroarch.cfg -L /opt/retropie/libretrocores/lr-glupen64/glupen64_libretro.so /home/pi/RetroPie/roms/n64/supermario64.n64
GNU gdb (Raspbian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/retropie/emulators/retroarch/bin/retroarch...done.
(gdb) tty /dev/tty1
(gdb) run
Starting program: /opt/retropie/emulators/retroarch/bin/retroarch --config /opt/retropie/configs/all/retroarch.cfg --appendconfig /opt/retropie/configs/n64/retroarch.cfg -L /opt/retropie/libretrocores/lr-glupen64/glupen64_libretro.so /home/pi/RetroPie/roms/n64/supermario64.n64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x76677460 (LWP 22155)]
[New Thread 0x71285460 (LWP 22156)]
[New Thread 0x6fa82460 (LWP 22157)]
[New Thread 0x6f282460 (LWP 22158)]
[New Thread 0x6ea82460 (LWP 22159)]
[New Thread 0x6e282460 (LWP 22160)]

Program received signal SIGSEGV, Segmentation fault.
0x000d5b4c in matrix_4x4_multiply (out=0x7effdd80, a=a@entry=0x7effdbb8, b=b@entry=0x0) at libretro-common/gfx/math/matrix_4x4.c:195
195	libretro-common/gfx/math/matrix_4x4.c: No such file or directory.
(gdb) 
```

i seem to get the same error with regular libretro-mupen64plus, but all my other cores are ok. not sure what could be up as i cleared my CFGs - perhaps something in the mupen-specific cfgs/inis. I will investigate more but just dumping all this here so I can get back to it later :)

**Comment by dankcushions** [comment]
Maybe this is related to https://github.com/libretro/RetroArch/issues/3517 - I'll recompile RA later tonight and retest.

**Comment by loganmc10** [comment]
Ya this seems like it's probably a RetroArch issue that is possibly fixed by

https://github.com/libretro/RetroArch/commit/3e9df72123c291123b7fd0c9ff7a114108300c0f

**Comment by dankcushions** [comment]
Just tried with latest RA and still the same error :/ 
```
Starting program: /opt/retropie/emulators/retroarch/bin/retroarch --config /opt/retropie/configs/all/retroarch.cfg --appendconfig /opt/retropie/configs/n64/retroarch.cfg -L /opt/retropie/libretrocores/lr-glupen64/glupen64_libretro.so /home/pi/RetroPie/roms/n64/supermario64.n64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x76677460 (LWP 8481)]
[New Thread 0x71285460 (LWP 8482)]
[New Thread 0x6fa82460 (LWP 8483)]
[New Thread 0x6f282460 (LWP 8484)]
[New Thread 0x6ea82460 (LWP 8485)]
[New Thread 0x6e282460 (LWP 8486)]

Program received signal SIGSEGV, Segmentation fault.
0x000d5c44 in matrix_4x4_multiply (out=0x7effdd90, a=a@entry=0x7effdbc8, b=b@entry=0x0) at libretro-common/gfx/math/matrix_4x4.c:195
```

it's surely an RA issue but i don't get why only i'm getting it? and only in the 2 n64 cores? i use the XMB if that makes a difference. i'll do a debug build and see if i can understand the issue better.

**Comment by loganmc10** [comment]
The N64 cores are the some of the only ones that use OpenGL, so that is probably the difference. You'd probably run into the same problem with reicast.

Sorry I haven't tried the git version of RetroArch on my Raspberry Pi in a while, I just run 1.3.6 since they make so many untested commits to the project, it's not a great program to run from the git version.

**Comment by dankcushions** [comment]
seems to be the same issue: http://libretro.com/forums/showthread.php?t=6688

i think you're right - GL core issue

**Comment by loganmc10** [comment]
Ya this is definitely a RetroArch issue affecting multiple cores, I'm going to close this issue as there is nothing I can do about it in this core.

They don't really look at or test things they commit to RetroArch, it's a pretty messy free-for-all. If I was you I would use the latest released version of RetroArch and use the git master version of the cores
