### ISSUE TITLE
Segfault in glsm.c

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#72]
OS: `Slackwar64-current`
`RetroArch-2016.10.08_f0ce438_master-x86_64-1_git`
`GLupeN64-2016.10.08_38135d6_master-x86_64-1_git`

I can reproduce this by playing Diddy Kong's Racing and after ~5 minutes the game will crash. This wasn't happening yesterday, maybe VEC4?
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffdf08b95d in rglBindFramebuffer (target=36009, framebuffer=0)
    at custom/glsm/glsm.c:1697
1697          framebuffer = hw_render.get_current_framebuffer();
```
GDB log - http://pastebin.com/JQnDXgYT

**Comment by loganmc10** [comment]
What an odd line to segfault on. Did you update RetroArch recently? hw_render.get_current_framebuffer() is actually a call to RetroArch to get the name of the current default framebuffer.

**Comment by loganmc10** [comment]
It points here:

https://github.com/libretro/RetroArch/blob/master/gfx/drivers/gl.c#L485-L489

But it looks like that hasn't been updated in a while, but who knows what else gets called inside that. I would try RetroArch from a few day ago and see if it still happens.

**Comment by loganmc10** [comment]
I suppose it could also be the case that ```hw_render``` is no longer valid, that is also a pointer to RetroArch info.

It's type is ```retro_hw_render_callback``` and it is retrieved by calling ```environ_cb(RETRO_ENVIRONMENT_SET_HW_RENDER, &hw_render)``` when the context is created. If that pointer somehow became invalid that would probably cause a segfault

**Comment by orbea** [comment]
Still occurs with `RetroArch-2016.10.05_db8eb90_master-x86_64-1_git`, but it doesn't with `GLupeN64-2016.10.06_0f9a823_master-x86_64-1_git`. I guess I can bisect it.

**Comment by orbea** [comment]
Git bisect failed.
```

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
a76d0e646fa7ec003707525c8d7cd819ef2a5fb4
83683a5822444df32821aa717cb4999c348bdf44
We cannot bisect more!
```

Something went wrong between the GLideN64 update and the compile fix. I tried upstream with the current master and was not able to reproduce it there though. Let me try your vbo branch.
a76d0e646fa7ec003707525c8d7cd819ef2a5fb4
83683a5822444df32821aa717cb4999c348bdf44

**Comment by orbea** [comment]
Nothing there either...

**Comment by orbea** [comment]
What is the range of commits for the GLideN64 update? I guess bisecting that might help...

**Comment by loganmc10** [comment]
Should be everything from today, so abcbe96095514afbc6f2255605f4088154aa32e8 to a5a432c4fd8762bdab5a0abd8545e841203592bc

**Comment by loganmc10** [comment]
Plus I had to add https://github.com/gonetz/GLideN64/pull/1162 (which was the "fix compile" commit)

**Comment by orbea** [comment]
```
85a5ae8ea15ba0b696c0b3d0ab17dd7d62753019 is the first bad commit
commit 85a5ae8ea15ba0b696c0b3d0ab17dd7d62753019
Author: Sergey Lipskiy <gonetz@ngs.ru>
Date:   Sun Sep 25 20:21:54 2016 +0700

    Implement performance counter.
    Implement drawing performance info on screen.

:040000 040000 ab6f203ed9e9e567036325b52fbfa75fd3553684 113853e28fda417d74bb87873b070346753c0f55 M	projects
:040000 040000 19cd8aee5cf85d340cc823fbc40edf10da5bcc5b e8928c06ab45dc66d00218d9707ea4dfdc7bc34e M	src

```
https://github.com/gonetz/GLideN64/commit/85a5ae8ea15ba0b696c0b3d0ab17dd7d62753019

This bisect two steps, for the first build I had to apply your compile fix, for the second I reversed the Makefile.common change.

**Comment by loganmc10** [comment]
I assume since this is happening after a period of time it has something to do with all the counting going on with the performance counter (some variable gets too big for its type over time?)

I have no idea why this only happens in glupen64, maybe because it compiles with -O3 or something? Who knows. I'll submit a pull request to GLideN64 to only count if it is actually displaying the performance stats on screen, since that shouldn't break anything and glupen64 doesn't use this feature anyway

**Comment by orbea** [comment]
Probably not the optimization, it occurs with `DEBUG=1` which uses `-O0`.

**Comment by loganmc10** [comment]
Ok I committed cc4d714a1b2b993a09b19565208751efcd96d037 which will stop it from making that call, it's still confusing why that GLideN64 commit would cause this problem though.

**Comment by orbea** [comment]
You're not going to like this. It still happens and now gdb gives me a corrupt stack.
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x000000000000812f in ?? ()
(gdb) bt 
#0  0x000000000000812f in ?? ()
#1  0x00007fffdf010ff9 in inputGetKeys_default (Control=0, Keys=0x1fd52b0)
    at custom/mupen64plus-core/plugin/emulate_game_controller_via_libretro.c:710
#2  0x00007fffdf011c35 in egcvip_get_input (opaque=0x7fffdf263170 <channels>)
    at custom/mupen64plus-core/plugin/emulate_game_controller_via_libretro.c:1040
#3  0x00007fffdeff5902 in game_controller_get_input (
    cont=0x7fffdffc6620 <g_si+96>)
    at mupen64plus-core/src/si/game_controller.c:170
#4  0x00007fffdeff5608 in read_controller_read_buttons (
    cont=0x7fffdffc6620 <g_si+96>, 
    cmd=0x7fffdffc65e1 <g_si+33> "\001\004\001\200")
    at mupen64plus-core/src/si/game_controller.c:64
#5  0x00007fffdeff59d2 in read_controller (cont=0x7fffdffc6620 <g_si+96>, 
    cmd=0x7fffdffc65e1 <g_si+33> "\001\004\001\200")
    at mupen64plus-core/src/si/game_controller.c:195
#6  0x00007fffdeff649c in update_pif_read (si=0x7fffdffc65c0 <g_si>)
    at mupen64plus-core/src/si/pif.c:232
#7  0x00007fffdeff67d5 in dma_si_read (si=0x7fffdffc65c0 <g_si>)
    at mupen64plus-core/src/si/si_controller.c:70
#8  0x00007fffdeff6999 in write_si_regs (opaque=0x7fffdffc65c0 <g_si>, 
    address=2759852036, value=532678592, mask=4294967295)
    at mupen64plus-core/src/si/si_controller.c:127
#9  0x00007fffdefca073 in writew (write_word=0x7fffdeff6919 <write_si_regs>, 
    opaque=0x7fffdffc65c0 <g_si>, address=2759852036, value=532678592)
    at mupen64plus-core/src/memory/memory.c:152
#10 0x00007fffdefcbc20 in write_si () at mupen64plus-core/src/memory/memory.c:817
#11 0x00007fffe3d86fda in ?? ()
#12 0x0000000101fd5450 in ?? ()
#13 0x00007fffdf009a65 in dyna_start (
    code=<error reading variable: Cannot access memory at address 0xffffffffffffffe8>) at mupen64plus-core/src/r4300/x86_64/rjump.c:64
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
GDB log - http://pastebin.com/tU0aB8Az

**Comment by loganmc10** [comment]
I figured, I don't know why it was deciding to segfault there but it was probably unrelated. I'll leave that commit though, fewer calls to RetroArch can never hurt 

I'll submit a pull request to GlideN64 to fully disable they performance counter stuff if it's not being used and hopefully they fixes it

**Comment by loganmc10** [comment]
I just committed 20bea0b8dfa3f38bea8968ddccacf4a0ab9fc1f8 which hopefully will fix this. If it does then I will submit that as a pull request to GLideN64

It might be because GLupeN64 (and mupen64plus-libretro) uses libco to switch between "talking to RetroArch" and running mupen64plus. Maybe it doesn't handle the clock/counting stuff well.

**Comment by loganmc10** [comment]
By the way if you wanted to see if libco was to blame you could try it without that commit and set the CPU Core to "Cached Interpreter" instead of "Dynamic Re-compiler" since the Cached Interpreter doesn't use libco

**Comment by orbea** [comment]
That fixes it, thanks!

It will segfault in the same way with the cached interpreter.

**Comment by loganmc10** [comment]
What a weird thing hey? I have no idea why it was segfaulting there.
