### ISSUE TITLE
Blue Textures? [Regression]

### ISSUE THREAD

**Issue by Awakened0** [loganmc10/GLupeN64#90]
Testing todays Windows build I noticed a blue texture on Yoshi's face in Smash Bros. and blue around the Nintendo and Treasure logos in Tsumi to Batsu (Sin and Punishment):

![image](https://cloud.githubusercontent.com/assets/4565863/19981825/e454e596-a1d9-11e6-91ee-bf28bf761608.png)

![image](https://cloud.githubusercontent.com/assets/4565863/19981832/eafd3f74-a1d9-11e6-9a3d-5f25dcb024c8.png)

**Comment by loganmc10** [comment]
This appears to be related to xxHash, the new texture caching algorithm I was trying out, a failed experiment I suppose!

I believe the funny-nosed Yoshi's should be fixed by 8160e66d625cd23dd81b0015d93445b625084a4d (buildbot is building it now), but you can check Smash Bros and the other game to make sure it's back to normal.

**Comment by Awakened0** [comment]
Looks like it's still happening in Sin and Punishment at least. 8160e66 is in the name at the bottom in the menu so it should be the latest.

**Comment by loganmc10** [comment]
The 2 problems were actually unrelated, the issue with Sin and Punishment came somewhere from this commit https://github.com/loganmc10/GLupeN64/commit/8839cfc71fe7060ab1c367c879a563b86c09cd20

I'll sort  it out tomorrow.

**Comment by loganmc10** [comment]
Ok should be fixed by 5bb059aac26c50d55b14da3c329311356828d785

**Comment by Awakened0** [comment]
Yep, thanks!
